services:
  # Portfolio with Ollama AI
  - type: web
    name: rishab-portfolio-ai
    runtime: docker
    region: oregon
    plan: starter
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true

  # Backend Poker Server
  - type: web
    name: poker-server
    runtime: node
    region: oregon
    plan: free
    rootDir: ./server
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: TWITTER_BEARER_TOKEN
        sync: false
        # Optional: Add this manually in Render dashboard for Twitter features
    autoDeploy: true

